namespace :db do
  desc "fill in Database"
  task :pages => :environment do

    #introduction tag line
    Page.create(name: "Introducing ApSolute Technology", page_content: "<p class='animated fadeInRightBig notransition container page-description2' style='box-sizing: border-box; margin: 15px auto 0px; padding-right: 15px; padding-left: 15px; width: 1170px; font-size: 17px; line-height: 30px; -webkit-animation: fadeInRightBig 1s 0.3s both; color: #161212; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;'>ApSolute Technologies was founded in the year 2013 by a group of dedicated professionals and young entrepreneur who strive for excellence all in their endeavors. ApSolute Technologies is a professional Web Development, Web Design and Software Development company. ApSolute Technology is offerings services in Website Development, Software Development, Web Design, eCommerce Development, Mobile Application Development and SEO. Our core business objective is to provide superior Managed IT Services and Solutions to corporate clients. Our mission is to achieve your 100% satisfaction, which is guaranteed by our professional service and friendly support with 24x7 support staff.</p> <p class='animated fadeInRightBig notransition container page-description2' style='box-sizing: border-box; margin: 15px auto 0px; padding-right: 15px; padding-left: 15px; width: 1170px; font-size: 17px; line-height: 30px; -webkit-animation: fadeInRightBig 1s 0.3s both; color: #161212; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;'>ApSolute Technologies assures that if your company is in need of any Offshore PHP, . Net, Desktop Application development, Web Design, Graphic Design and Mobile Application Development then definitely choose us. We are sure that our relations will be mutually beneficial, and we will be able to satisfy your needs and meet all your standards.Our experienced and talented professionals are committed to give quality output, and to meet all the challenges to provide the best results. Our Web and Software developers have the expertise to accomplish all challenging tasks comfortably. Our Core Team of skilled perofessional will ensure that time spent with us will be a pleasure and also being productive. Apsolute Technologies is proud of its achievements and is committed to going even further.</p>") unless Page.find_by(name: "Introducing ApSolute Technology").present?

    #about us
    Page.create(name: "About us",                        page_content: "<p>ApSolute Technologies was founded in the year 2013 by a group of dedicated professionals and young entrepreneur who strive for excellence all in their endeavors. ApSolute Technologies is a professional Web Development, Web Design and Software Development company. ApSolute Technology is offerings services in Website Development, Software Development, Web Design, eCommerce Development, Mobile Application Development and SEO. Our core business objective is to provide superior Managed IT Services and Solutions to corporate clients. Our mission is to achieve your 100% satisfaction, which is guaranteed by our professional service and friendly support with 24x7 support staff.</p> <p>ApSolute Technologies assures that if your company is in need of any Offshore PHP, . Net, Desktop Application development, Web Design, Graphic Design and Mobile Application Development then definitely choose us. We are sure that our relations will be mutually beneficial, and we will be able to satisfy your needs and meet all your standards.Our experienced and talented professionals are committed to give quality output, and to meet all the challenges to provide the best results. Our Web and Software developers have the expertise to accomplish all challenging tasks comfortably. Our Core Team of skilled perofessional will ensure that time spent with us will be a pleasure and also being productive. Apsolute Technologies is proud of its achievements and is committed to going even further.</p>") unless Page.find_by(name: "About us").present?
    Page.create(name: "About us discription line",       page_content: "ApSolute Technologies aims to turn your imagination real.") unless Page.find_by(name: "About us discription line").present?
    Page.create(name: "Our Mission",                     page_content: "<p><span style='color: #161212; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 17px; line-height: 30px;'>Our team has been built creatively, effectively and passionately to offer world class, comprehensive yet cost-effective IT solutions and services to our Global clienteles enabling to face any challenges.</span></p>") unless Page.find_by(name: "Our Mission").present?
    Page.create(name: "Our Vision",                      page_content: "<p><span style='color: #161212; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 17px; line-height: 30px;'>To be a globally acclaimed web solution company known for reliable support system, Customer satisfaction responsiveness, constantly strive to excellence with value added solutions, state of the art technology and cost effective solutions ApSolute Technologies was founded in the year 2013 by a group of dedicated professionals and young entrepreneur who strive for excellence all in their endeavors. ApSolute Technologies is a professional Web Development, Web Design and Software Development company. ApSolute Technology is offerings services in Website Development, Software Development, Web Design, eCommerce Development, Mobile Application Development and SEO. Our core business objective is to provide superior Managed IT Services and Solutions to corporate clients. Our mission is to achieve your 100% satisfaction, which is guaranteed by our professional service and friendly support with 24x7 support staff.</span></p>") unless Page.find_by(name: "Our Vision").present?

    #contact
    Page.create(name: "Contact",                         page_content: "<p>If you're not failing every now and again, it's a sign you're not doing anything very innovative. If my films don't show a profit, I know I'm doing something right.</p>") unless Page.find_by(name: "Contact").present?
    Page.create(name: "Address",                         page_content: "Ahmedabad, Gujarat , India") unless Page.find_by(name: "Address").present?
    Page.create(name: "Phone",                           page_content: "(+91) 79 40326868") unless Page.find_by(name: "Phone").present?
    Page.create(name: "Email",                           page_content: "apsolutetechnology@gmail.com") unless Page.find_by(name: "Email").present?

    #services
    Page.create(name: "Service Mobile Development",              page_content: "<p>ApSolute Technologies offer complete Android/IPhone /Widnows/BlackBarry Apps Development Solutions and has established expertise in mobile space. The company provides complete Android Apps Development Lifecycle ranging from conceptualization, designing, development, integration, testing, app store deployment and maintenance. Apart from this company also offers value added services such as Android Apps Testing and Android Porting-Migration Services.</p>") unless Page.find_by(name: "Service Mobile Development").present?
    Page.create(name: "Service Website Development",             page_content: "<p>Are your getting your website updated regularly? If yes, are you spending a hoarded wealth on website maintenance? Does your website maintenance company take too long to take care of your needs? Our website maintenance package enables us to manage your site while you get on with your business! Once your website is launched we undertake a whole range of key activities to accomplish the website maintenance activities.</p>") unless Page.find_by(name: "Service Website Development").present?
    Page.create(name: "Service SEO & Designing",                 page_content: "<p>Have you been in search for the best web design company to get your corporate website designed? Do you want your website to stand out from the rest of the competition? Do you want to launch a website that performs well online? We have the best answers for all your requirements. We offer the most comprehensive range of web design services. We offer top-notch web design services that will help you impress your customers.</p>") unless Page.find_by(name: "Service SEO & Designing").present?
  end

end